
services:
  gateway:
    image: caddy:2.6.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - gateway-data:/data
      - gateway-config:/config

    networks:
      - ygp-network

volumes:
  gateway-data:
  gateway-config:


networks:
  ygp-network :
    external: true

